name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild src\UnlockerIsland\UnlockerIsland.sln /p:Configuration=Release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UnlockerIsland-build
        path: src\UnlockerIsland\x64\Release\*.dll


